//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mapApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahalle
    {
        public int MAH_KODU { get; set; }
        public string MAH_ADI { get; set; }
        public string KOORDINAT { get; set; }
    }
}
